[Template merge - und] Major bug fix to the generate lemma test script. Now it actually checks that the generated lemmas correspond to the listed ones. Several of the languages had local modifications. Those are brought forward to the new version, to my best effort.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/rus@94064 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-noun-lemmas.sh.in b/test/src/morphology/generate-noun-lemmas.sh.in
--- a/test/src/morphology/generate-noun-lemmas.sh.in
+++ b/test/src/morphology/generate-noun-lemmas.sh.in
@@ -17,6 +17,7 @@ lemmas=./nouns.txt
 generatedlemmas=./gen-nouns
 failedlemmas=./fail-lemmas
 generatorfile=./../../../src/generator-gt-norm
+resultfile=lemma-gen-diff
 
 # FAIL if source file does not exist:
 if [ ! -f $sourcefile ]; then
@@ -63,29 +64,68 @@ for f in $fsttype; do
 	fi
 	if [ -f "$generatorfile.$f" ]; then
 		let "transducer_found += 1"
-		sed 's/$/+N+Neu+Sg+Nom/' $lemmas | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.neu.txt
-		fgrep '?' $generatedlemmas.$f.neu.txt | cut -f1 | cut -d'+' -f1 \
-				| sed 's/$/+N+Msc+Sg+Nom/' | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.msc.txt
-		fgrep '?' $generatedlemmas.$f.msc.txt | cut -f1 | cut -d'+' -f1 \
-				| sed 's/$/+N+Fem+Sg+Nom/' | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.fem.txt
-		fgrep '?' $generatedlemmas.$f.fem.txt | cut -f1 | cut -d'+' -f1 \
-				| sed 's/$/+N+Neu+Pl+Nom/' | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.neupl.txt
-		fgrep '?' $generatedlemmas.$f.neupl.txt | cut -f1 | cut -d'+' -f1 \
-				| sed 's/$/+N+Msc+Pl+Nom/' | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.mscpl.txt
-		fgrep '?' $generatedlemmas.$f.mscpl.txt | cut -f1 | cut -d'+' -f1 \
-				| sed 's/$/+N+Fem+Pl+Nom/' | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.fempl.txt
-		fgrep '?' $generatedlemmas.$f.fempl.txt > $failedlemmas.$f.txt
-		if [ $(wc -l $failedlemmas.$f.txt | tr -s ' ' | sed 's/^ //' \
-				| cut -d' ' -f1) -gt 0 ]; then
+
+###### Test non-comopunds: #######
+		# generate Neuter Singular:
+		sed 's/$/+N+Neu+Sg+Nom/' $lemmas | $lookuptool $generatorfile.$f \
+			| cut -f2  > $generatedlemmas.$f.tmp.txt
+		fgrep -v "+N+Sg" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
+			| sort -u  > $generatedlemmas.$f.txt
+		fgrep    "+N+Sg" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
+			| sort -u  > $failedlemmas.$f.txt
+		# generate Masc Singular:
+		sed 's/$/+N+Msc+Sg+Nom/' $failedlemmas.$f.txt \
+			| $lookuptool $generatorfile.$f \
+			| cut -f2  > $generatedlemmas.$f.tmp.txt
+		fgrep -v "+N+Sg" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
+			| sort -u >> $generatedlemmas.$f.txt
+		fgrep    "+N+Sg" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
+			| sort -u  > $failedlemmas.$f.txt
+		# generate Fem Singular:
+		sed 's/$/+N+Fem+Sg+Nom/' $failedlemmas.$f.txt \
+			| $lookuptool $generatorfile.$f \
+			| cut -f2  > $generatedlemmas.$f.tmp.txt
+		fgrep -v "+N+Sg" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
+			| sort -u >> $generatedlemmas.$f.txt
+		fgrep    "+N+Sg" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
+			| sort -u  > $failedlemmas.$f.txt
+		# generate Neuter Plural:
+		sed 's/$/+N+Neu+Pl+Nom/' $failedlemmas.$f.txt \
+			| $lookuptool $generatorfile.$f \
+			| cut -f2  > $generatedlemmas.$f.tmp.txt
+		fgrep -v "+N+Sg" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
+			| sort -u >> $generatedlemmas.$f.txt
+		fgrep    "+N+Sg" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
+			| sort -u  > $failedlemmas.$f.txt
+		# generate Masc Plural:
+		sed 's/$/+N+Msc+Pl+Nom/' $failedlemmas.$f.txt \
+			| $lookuptool $generatorfile.$f \
+			| cut -f2  > $generatedlemmas.$f.tmp.txt
+		fgrep -v "+N+Sg" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
+			| sort -u >> $generatedlemmas.$f.txt
+		fgrep    "+N+Sg" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
+			| sort -u  > $failedlemmas.$f.txt
+		# generate Fem Plural:
+		sed 's/$/+N+Fem+Pl+Nom/' $failedlemmas.$f.txt \
+			| $lookuptool $generatorfile.$f \
+			| cut -f2  > $generatedlemmas.$f.tmp.txt
+		fgrep -v "+N+Sg" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
+			| sort -u >> $generatedlemmas.$f.txt
+		fgrep    "+N+Sg" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
+			| sort -u  > $failedlemmas.$f.txt
+
+###### Collect results: #######
+		# Sort and compare original input with resulting output - the diff is
+		# stored and opened in SEE:
+		sort -u -o $generatedlemmas.$f.txt $generatedlemmas.$f.txt 
+		comm -23 $lemmas $generatedlemmas.$f.txt > $resultfile.$f.txt
+
+		# if at least one word is found, the test failed, and the list of failed
+		# lemmas is opened in SubEthaEdit:
+		if [ -s $resultfile.$f.txt ]; then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $failedlemmas.$f.txt
+				$EXTEDITOR $resultfile.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -105,5 +145,5 @@ fi
 
 if [ $transducer_found -eq 0 ]; then
     echo ERROR: No transducer found
-    exit 1
+    exit 77
 fi
