repairing make check scripts. Proper nouns are expected to fail because many of the lexc entries have lemma names continued in the continuation class (i.e. the lemma-scraping script returns strings that are not complete lemmas.)
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/rus@110519 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-verb-lemmas.sh.in b/test/src/morphology/generate-verb-lemmas.sh.in
--- a/test/src/morphology/generate-verb-lemmas.sh.in
+++ b/test/src/morphology/generate-verb-lemmas.sh.in
@@ -7,22 +7,36 @@
 # - an exit status of 99 a hard error
 # - any other exit status will denote a failure.
 
+# To run this test script only, do:
+#
+# make check TESTS=generate-noun-lemmas.sh
 
-# Test that all verb lemmas do generate as themselves:
-
+# This test script will test that all noun lemmas do generate as themselves.
+# Extend as needed, and copy to new files to adapt to other parts of speech.
+# The changes usually needed are:
+#
+# 1. change the reference to the source file (line 23)
+# 2. extend the extract lemmas egrep expression (lines 53 ff)
+# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
 ###### Variables: #######
-sourcefile=${srcdir}/../../../src/morphology/stems/verbs.lexc
-lemmas=./verbs.txt
-generatedlemmas=./gen-verbs
-failedlemmas=./fail-verb-lemmas
-generatorfile=./../../../src/generator-gt-norm
-resultfile=lemma-gen-verb-diff
+POS=verbs
+### in ###
+source_file=${srcdir}/../../../src/morphology/stems/${POS}.lexc
+generator_file=./../../../src/generator-gt-norm
+analyser_file=./../../../src/analyser-gt-norm
 
-# FAIL if source file does not exist:
-if [ ! -f $sourcefile ]; then
+### out ###
+lemmas=./filtered-${POS}
+generated_lemmas=./generated-${POS}
+result_file=missing_${POS}_lemmas
+gen_result_file=generated_missing_${POS}_lemmas
+ana_result_file=analysed_missing_${POS}_lemmas
+
+# SKIP if source file does not exist:
+if [ ! -f $source_file ]; then
     echo
-    echo "*** Warning: Source file $sourcefile not found."
+    echo "*** Warning: Source file $source_file not found."
     echo
     exit 77
 fi
@@ -43,9 +57,11 @@ fi
 EXTEDITOR=@SEE@
 pythonbin=@PYTHON@
 
-###### Extraction: #######
+##### Extract lemmas - add additional egrep pattern as parameters: #####
+##### --include "(pattern1|pattern2|...)"                          #####
+##### --exclude "(pattern1|pattern2|...)"                          #####
 @GTCORE@/scripts/extract-lemmas.sh \
-	$sourcefile "(CmpN/Last)" > $lemmas
+    $source_file > $lemmas
 
 ###### Start testing: #######
 transducer_found=0
@@ -53,39 +69,64 @@ Fail=0
 
 # The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
-	if [ $f == "xfst" ]; then
-		lookuptool="@LOOKUP@ -q -flags mbTT"
-		suffix="xfst"
-	elif [ $f == "hfst" ]; then
-		lookuptool="@HFST_OPTIMIZED_LOOKUP@ -q"
-		suffix="hfstol"
-	else
-	    Fail=1
-		printf "ERROR: Unknown fst type! "
-	    echo "$f - FAIL"
-	    continue
-	fi
-	if [ -f "$generatorfile.$suffix" ]; then
-		let "transducer_found += 1"
+    if [ $f == "xfst" ]; then
+        lookup_tool="@LOOKUP@ -q -flags mbTT"
+        suffix="xfst"
+    elif [ $f == "hfst" ]; then
+        lookup_tool="@HFST_OPTIMIZED_LOOKUP@ -q"
+        suffix="hfstol"
+    else
+        Fail=1
+        printf "ERROR: Unknown fst type! "
+        echo "$f - FAIL"
+        continue
+    fi
+    if [ -f "$generator_file.$suffix" ]; then
+        let "transducer_found += 1"
 
-###### Test non-compounds: #######
-		cat $lemmas | $pythonbin ${srcdir}/lemmaStager.py verb | $lookuptool \
-			$generatorfile.$suffix | $pythonbin ${srcdir}/lemmaChecker.py \
-			> $resultfile.$f.txt
+###### Test lemma generation: #######
+        # generate lemmas in singular, extract the resulting generated lemma,
+        # store it:
+		cat $lemmas | $pythonbin ${srcdir}/lemmaStager.py verb \
+			| $lookup_tool $generator_file.$suffix \
+			| $pythonbin ${srcdir}/lemmaChecker.py \
+			> $result_file.$f.txt
+			
+###### Collect results, and generate debug info if FAIL: #######
+        # Sort and compare original input with resulting output - the diff is
+        # used to generate lemmas which are opened in SEE:
+        #sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
+        #comm -23 $lemmas $generated_lemmas.$f.txt > $result_file.$f.txt
 
-		# if at least one word is found, the test failed, and the list of failed
-		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]; then
-			# Only open the failed lemmas in see if @SEE@ is defined:
-			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
-			fi
-		    Fail=1
-		    echo "$f - FAIL"
-		    continue
-		fi
-	    echo "$f - PASS"
-	fi
+        # Open the diff file in SubEthaEdit (if there is a diff):
+        if [ -s $result_file.$f.txt ]; then
+            #grep -v '^$' $result_file.$f.txt \
+            #  | sed 's/$/+N+Sg+Nom/' \
+            #  | $lookup_tool $generator_file.$suffix \
+            #  > $gen_result_file.$f.txt
+            # If we have an analyser, analyse the missing lemmas as well:
+            if test -e $analyser_file.$suffix ; then
+                grep -v '^$' $result_file.$f.txt \
+                  | $lookup_tool $analyser_file.$suffix \
+                  > $ana_result_file.$f.txt
+            fi
+            # Only open the failed lemmas in see if @SEE@ is defined:
+            if [ "$EXTEDITOR" ]; then
+                $EXTEDITOR $result_file.$f.txt
+                $EXTEDITOR $gen_result_file.$f.txt
+                $EXTEDITOR $ana_result_file.$f.txt
+            else
+                echo "There where problem lemmas. Details in:"
+                echo "* $result_file.$f.txt    "
+                echo "* $gen_result_file.$f.txt"
+                echo "* $ana_result_file.$f.txt"
+            fi
+            Fail=1
+            echo "$f - FAIL"
+            continue
+        fi
+        echo "$f - PASS"
+    fi
 done
 
 # When done, remove the generated data file:
@@ -93,7 +134,7 @@ rm -f $lemmas
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
-	exit 1
+    exit 1
 fi
 
 if [ $transducer_found -eq 0 ]; then
